### ISSUE TITLE
build on linux error

### ISSUE THREAD

**Issue by kuchaguangjie** [EugenyN/TanksKombat#4]
on linux, build via `axmol build`, get error:

> 1kiss: cmake --build /mnt/mars/git_repository/axmol_repo/TanksKombat/build --config Release --parallel 8 --target TanksKombat
> gmake: Makefile: No such file or directory
> gmake: *** No rule to make target 'Makefile'.  Stop.
> 1kiss: Build done
> 

any suggestion ?

**Comment by EugenyN** [comment]
I did not add a Linux build for this project, because I do not have the appropriate environment. You can add it yourself using examples and templates from axmol
